name: Build neovim image
run-name: Build Neovim image yay
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 3 */10 * *'

env:
  IMAGE: forgejo.maciej.cloud/pkg/neovim
jobs:
  build-neovim-arm64:
    runs-on: arm64
    steps:
      - name: install actions deps
        run: | 
          dnf install -y nodejs git
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          podman build --ulimit nofile=10240:10240 . --tag $IMAGE:arm64
      - name: login to registry
        run: |
          podman login -u "${{ secrets.PACKAGES_USERNAME }}" -p "${{ secrets.PACKAGES_PASSWD }}" forgejo.maciej.cloud
      - name: Push image
        run: |
          podman push $IMAGE:arm64
  build-neovim-amd64:
    runs-on: amd64
    steps:
      - name: install actions deps
        run: | 
          dnf install -y nodejs git
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          podman build --ulimit nofile=10240:10240 . --tag $IMAGE:amd64
      - name: login to registry
        run: |
          podman login -u "${{ secrets.PACKAGES_USERNAME }}" -p "${{ secrets.PACKAGES_PASSWD }}" forgejo.maciej.cloud
      - name: Push image
        run: |
          podman push $IMAGE:amd64
  update-images-manifest:
    runs-on: [ amd64 ]
    needs: 
      - build-neovim-arm64
      - build-neovim-amd64
    steps:
      - name: login to registry
        run: podman login -u "${{ secrets.PACKAGES_USERNAME }}" -p "${{ secrets.PACKAGES_PASSWD }}" forgejo.maciej.cloud
      - name: Create manifest and push
        run: | 
          echo "Updating manifest for neovim";
          podman manifest create $IMAGE:latest $IMAGE:amd64 $IMAGE:arm64;
          podman manifest push $IMAGE:latest $IMAGE:latest;
