name: Build neovim image
run-name: Build Neovim image yay
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 3 */3 * *'

jobs:
  build-neovim:
    runs-on: ubuntu-latest
    steps:
      - name: install actions deps
        run: | 
          dnf install -y nodejs git
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: podman build . --file Dockerfile --tag neovim:latest
      - name: build image
        run: podman login -u "${{ secrets.PACKAGES_USERNAME }}" -p "${{ secrets.PACKAGES_PASSWD }}" gitea.maciej.cloud
      - name: Push image
        run: |
          IMAGE_NAME="neovim"
          IMAGE_ID="gitea.maciej.cloud/packages/$IMAGE_NAME"
          podman tag $IMAGE_NAME:latest $IMAGE_ID:latest
          podman pull $IMAGE_ID:v1
          podman pull $IMAGE_ID:v2
          podman tag $IMAGE_ID:v2 $IMAGE_ID:v3
          podman tag $IMAGE_ID:v1 $IMAGE_ID:v2
          podman tag $IMAGE_ID:latest $IMAGE_ID:v1
          podman push $IMAGE_ID:latest
          podman push $IMAGE_ID:v1
          podman push $IMAGE_ID:v2
          podman push $IMAGE_ID:v3
